name = "OolongEval"
uuid = "2721bf49-7272-4fd8-83e5-8e4f37d4728f"
authors = ["Jun Tian <tianjun.cpp@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[compat]
TestItemRunner = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
